-- Generated by Oracle SQL Developer Data Modeler 24.3.1.347.1153
--   at:        2026-02-12 14:40:15 EST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE categorie (
    id_categorie  INTEGER NOT NULL,
    nom_categorie VARCHAR2(50 CHAR) NOT NULL
);

COMMENT ON COLUMN categorie.id_categorie IS
    'Le ID unique de la catégorie';

COMMENT ON COLUMN categorie.nom_categorie IS
    'Nom du catégorie';

ALTER TABLE categorie ADD CONSTRAINT categorie_pk PRIMARY KEY ( id_categorie );

CREATE TABLE commande (
    id_commande      INTEGER NOT NULL,
    date_commande    DATE NOT NULL,
    statut           VARCHAR2(50 CHAR) NOT NULL,
    panier_id_panier INTEGER NOT NULL,
    quantite         INTEGER NOT NULL,
    prix             NUMBER(10, 2) NOT NULL
);

COMMENT ON COLUMN commande.id_commande IS
    'Le ID unique de la commande.';

COMMENT ON COLUMN commande.date_commande IS
    'La date du départ de la commande.';

COMMENT ON COLUMN commande.statut IS
    'Le statut de la commande (Payé, livré, en cours)';

CREATE UNIQUE INDEX commande__idx ON
    commande (
        panier_id_panier
    ASC );

ALTER TABLE commande ADD CONSTRAINT commande_pk PRIMARY KEY ( id_commande );

CREATE TABLE panier (
    id_panier                  INTEGER NOT NULL,
    utilisateur_id_utilisateur INTEGER NOT NULL,
    date_creation              DATE NOT NULL
);

COMMENT ON COLUMN panier.id_panier IS
    'Le ID unique du panier créée par un utilisateur';

COMMENT ON COLUMN panier.date_creation IS
    'Date de création du panier';

CREATE UNIQUE INDEX panier__idx ON
    panier (
        utilisateur_id_utilisateur
    ASC );

ALTER TABLE panier ADD CONSTRAINT panier_pk PRIMARY KEY ( id_panier );

CREATE TABLE "Panier-Produit" (
    panier_id_panier   INTEGER NOT NULL,
    produit_id_produit INTEGER NOT NULL,
    quantite           INTEGER
);

ALTER TABLE "Panier-Produit" ADD CONSTRAINT "Panier-Produit_PK" PRIMARY KEY ( panier_id_panier,
                                                                              produit_id_produit );

CREATE TABLE produit (
    id_produit     INTEGER NOT NULL,
    specs_id_specs INTEGER NOT NULL,
    nom            VARCHAR2(50 CHAR) NOT NULL,
    description    VARCHAR2(1000 CHAR),
    prix           NUMBER(10, 2) NOT NULL,
    stock          INTEGER NOT NULL
);

COMMENT ON COLUMN produit.id_produit IS
    'Le ID unique du produit.';

COMMENT ON COLUMN produit.nom IS
    'Le nom du produit.';

COMMENT ON COLUMN produit.description IS
    'La description du produit.';

COMMENT ON COLUMN produit.prix IS
    'Le prix en decimal du produit (en $).';

COMMENT ON COLUMN produit.stock IS
    'Nombre de stock';

CREATE UNIQUE INDEX produit__idx ON
    produit (
        specs_id_specs
    ASC );

ALTER TABLE produit ADD CONSTRAINT produit_pk PRIMARY KEY ( id_produit );

CREATE TABLE "Produit-Categorie" (
    produit_id_produit     INTEGER NOT NULL,
    categorie_id_categorie INTEGER NOT NULL
);

ALTER TABLE "Produit-Categorie" ADD CONSTRAINT "Produit-Categorie_PK" PRIMARY KEY ( produit_id_produit,
                                                                                    categorie_id_categorie );

CREATE TABLE specs (
    id_specs             INTEGER NOT NULL,
    produit_id_produit   INTEGER NOT NULL,
    type_produit         VARCHAR2(20 CHAR) NOT NULL,
    processeur           VARCHAR2(50 CHAR),
    frequence_processeur INTEGER,
    taille_ram           INTEGER,
    type_ram             VARCHAR2(50 CHAR),
    taille_stockage      INTEGER,
    type_stockage        VARCHAR2(50 CHAR),
    carte_graphique      VARCHAR2(50 CHAR)
);

COMMENT ON COLUMN specs.id_specs IS
    'Le ID unique de spec.';

COMMENT ON COLUMN specs.type_produit IS
    'Type du produit (ordinateur ou composant)';

COMMENT ON COLUMN specs.processeur IS
    'Composant: processeur/CPU. Nom';

COMMENT ON COLUMN specs.frequence_processeur IS
    'Composant: Processeur. Fréquence (en GHz)';

COMMENT ON COLUMN specs.taille_ram IS
    'Composant: RAM. Taille (en Go)';

COMMENT ON COLUMN specs.type_ram IS
    'Composant: RAM. Type (DRAM: dynamique, SRAM: statique...)';

COMMENT ON COLUMN specs.taille_stockage IS
    'Composant: stockage. Taille (en Go)';

COMMENT ON COLUMN specs.type_stockage IS
    'Composant: stockage. Type (SSD, HDD...)';

COMMENT ON COLUMN specs.carte_graphique IS
    'Composant: Carte graphique/GPU: Nom';

CREATE UNIQUE INDEX specs__idx ON
    specs (
        produit_id_produit
    ASC );

ALTER TABLE specs ADD CONSTRAINT specs_pk PRIMARY KEY ( id_specs );

CREATE TABLE utilisateur (
    id_utilisateur   INTEGER NOT NULL,
    nom              VARCHAR2(50 CHAR) NOT NULL,
    prenom           VARCHAR2(50 CHAR) NOT NULL,
    mot_de_passe     VARCHAR2(100 CHAR) NOT NULL,
    courriel         VARCHAR2(50 CHAR) NOT NULL,
    adresse          VARCHAR2(50 CHAR),
    role             VARCHAR2(50 CHAR) NOT NULL,
    panier_id_panier INTEGER NOT NULL
);

COMMENT ON COLUMN utilisateur.id_utilisateur IS
    'Le ID unique de l''utilisateur';

COMMENT ON COLUMN utilisateur.nom IS
    'Le nom de famille de l''utilisateur.';

COMMENT ON COLUMN utilisateur.prenom IS
    'Le prénom de l''utilisateur.';

COMMENT ON COLUMN utilisateur.mot_de_passe IS
    'Le mot de passe associé au compte de l''utilisateur.';

COMMENT ON COLUMN utilisateur.courriel IS
    'Le courriel associé au compte de l''utilisateur';

COMMENT ON COLUMN utilisateur.role IS
    'Le role de l''utilisateur (client, admin)';

CREATE UNIQUE INDEX utilisateur__idx ON
    utilisateur (
        panier_id_panier
    ASC );

ALTER TABLE utilisateur ADD CONSTRAINT utilisateur_pk PRIMARY KEY ( id_utilisateur );

ALTER TABLE commande
    ADD CONSTRAINT commande_panier_fk FOREIGN KEY ( panier_id_panier )
        REFERENCES panier ( id_panier );

ALTER TABLE panier
    ADD CONSTRAINT panier_utilisateur_fk FOREIGN KEY ( utilisateur_id_utilisateur )
        REFERENCES utilisateur ( id_utilisateur );

ALTER TABLE "Panier-Produit"
    ADD CONSTRAINT "Panier-Produit_Panier_FK" FOREIGN KEY ( panier_id_panier )
        REFERENCES panier ( id_panier );

ALTER TABLE "Panier-Produit"
    ADD CONSTRAINT "Panier-Produit_Produit_FK" FOREIGN KEY ( produit_id_produit )
        REFERENCES produit ( id_produit );

ALTER TABLE produit
    ADD CONSTRAINT produit_specs_fk FOREIGN KEY ( specs_id_specs )
        REFERENCES specs ( id_specs );

ALTER TABLE "Produit-Categorie"
    ADD CONSTRAINT "Produit-Categorie_Categorie_FK" FOREIGN KEY ( categorie_id_categorie )
        REFERENCES categorie ( id_categorie );

ALTER TABLE "Produit-Categorie"
    ADD CONSTRAINT "Produit-Categorie_Produit_FK" FOREIGN KEY ( produit_id_produit )
        REFERENCES produit ( id_produit );

ALTER TABLE specs
    ADD CONSTRAINT specs_produit_fk FOREIGN KEY ( produit_id_produit )
        REFERENCES produit ( id_produit );

ALTER TABLE utilisateur
    ADD CONSTRAINT utilisateur_panier_fk FOREIGN KEY ( panier_id_panier )
        REFERENCES panier ( id_panier );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             5
-- ALTER TABLE                             17
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
